// Єдине джерело даних про ігри — використовується і app.mjs (динамічний сервер), і build.mjs (статична збірка)
export const gameList = [
  {
    id: 'hermitate',
    category: 'story-based-games',
    image: 'hermitate_ava.jpg',
    name: 'Hermitate',
    langKey: 'hermitate_description',
    media: [
      { type: 'video', youtubeId: 'YDi8QKWQaB8' },
      { type: 'image', url: 'hermitate/hermitate_screen1.jpg' },
      { type: 'image', url: 'hermitate/hermitate_screen3.jpg' },
      { type: 'image', url: 'hermitate/hermitate_screen2.jpg' },
      { type: 'image', url: 'hermitate/hermitate_screen4.jpg' },
      { type: 'image', url: 'hermitate/hermitate_screen5.jpg' },
      { type: 'image', url: 'hermitate/hermitate_screen6.jpg' },
      { type: 'image', url: 'hermitate/hermitate_screen7.jpg' },
      { type: 'image', url: 'hermitate/hermitate_screen8.jpg' },
      { type: 'image', url: 'hermitate/hermitate_screen9.jpg' },
      { type: 'image', url: 'hermitate/hermitate_screen10.jpg' },
      { type: 'video', youtubeId: 'PKmnsPFFdFk' },
      { type: 'video', youtubeId: '4baDydiZHTs' }
    ]
  },
  {
    id: 'the-safe-place',
    category: 'story-based-games',
    image: 'safe_place_ava.png',
    name: 'The Safe Place',
    langKey: 'the_safe_place_description',
    steamLink: 'https://store.steampowered.com/app/1917830/The_Safe_Place/',
    xBoxLink: 'https://anatolii.itch.io/the-safe-place',
    nintendoLink: 'https://www.nintendo.com/us/store/products/the-safe-place-switch',
    itchLink: 'https://anatolii.itch.io/the-safe-place',
    media: [
      { type: 'video', youtubeId: 'J_pMjO-Jvz4' },
      { type: 'image', url: 'safe_place/safe_place_screen1.jpg' },
      { type: 'image', url: 'safe_place/safe_place_screen3.jpg' },
      { type: 'image', url: 'safe_place/safe_place_screen2.jpg' },
      { type: 'image', url: 'safe_place/safe_place_screen4.jpg' },
      { type: 'image', url: 'safe_place/safe_place_screen5.jpg' },
      { type: 'image', url: 'safe_place/safe_place_screen6.jpg' },
      { type: 'image', url: 'safe_place/safe_place_screen7.jpg' },
      { type: 'image', url: 'safe_place/safe_place_screen8.jpg' },
      { type: 'image', url: 'safe_place/safe_place_screen9.jpg' },
      { type: 'image', url: 'safe_place/safe_place_screen10.jpg' },
      { type: 'video', youtubeId: 'GIJJvIBgmA4' },
      // { type: 'video', youtubeId: 'h9dARjD_ORg' },
      // { type: 'video', youtubeId: 'P3nYGa_GMw4' },
      // { type: 'video', youtubeId: 'hEhcmDLQDL8' },
      // { type: 'video', youtubeId: '3Q-RbZtDfjA' },
      // { type: 'video', youtubeId: 'qqAY45uT5vs' },
      // { type: 'video', youtubeId: '_12ec2Ypzm8' },
    ]
  },
  {
    id: 'repentant',
    category: 'story-based-games',
    image: 'repentant_ava.png',
    name: 'Repentant',
    langKey: 'repentant_description',
    steamLink: 'https://store.steampowered.com/app/874370/Repentant/',
    xBoxLink: 'https://www.xbox.com/ru-ru/games/store/repentant/9n52lrvrfgd7',
    nintendoLink: 'https://www.nintendo.com/us/store/products/repentant-switch/',
    itchLink: 'https://anatolii.itch.io/repentant',
    media: [
      { type: 'video', youtubeId: 'gEBn_xNvZT8' },
      // { type: 'video', youtubeId: 'Tcq82slo35k' },
      // { type: 'video', youtubeId: 'iJ2xPO78kx4' },
      { type: 'image', url: 'repentant/repentant_screen1.jpg' },
      { type: 'image', url: 'repentant/repentant_screen3.jpg' },
      { type: 'image', url: 'repentant/repentant_screen2.jpg' },
      { type: 'image', url: 'repentant/repentant_screen4.jpg' },
      { type: 'image', url: 'repentant/repentant_screen5.jpg' },
      { type: 'image', url: 'repentant/repentant_screen6.jpg' },
      { type: 'image', url: 'repentant/repentant_screen7.jpg' },
      { type: 'image', url: 'repentant/repentant_screen8.jpg' },
      { type: 'image', url: 'repentant/repentant_screen9.jpg' },
      { type: 'image', url: 'repentant/repentant_screen10.jpg' },
    ]
  },
  {
    id: 'little-kite',
    category: 'story-based-games',
    image: 'little_kite_ava.jpg',
    name: 'Little Kite',
    langKey: 'little_kite_description',
    steamLink: 'https://store.steampowered.com/app/610120/Little_Kite/',
    xBoxLink: 'https://www.xbox.com/ru-RU/games/store/little-kite/9N2F22FSLR8B',
    nintendoLink: 'https://www.nintendo.com/us/store/products/little-kite-switch/',
    itchLink: 'https://anatolii.itch.io/little-kite',
    media: [
      { type: 'video', youtubeId: 'k1jV5kuuS3A' },
      // { type: 'video', youtubeId: 'iWMUDAUCABM' },
      // { type: 'video', youtubeId: 'pgH8q9TJv2Y' },
      // { type: 'video', youtubeId: 'KCOMnFE6k5w' },
      // { type: 'video', youtubeId: 'stuIuplOykw' },
      // { type: 'video', youtubeId: 'c0eD-3--8dQ' },
      // { type: 'video', youtubeId: '87GZZ82VWqM' },
      { type: 'image', url: 'the_little_kite/the_little_kite_screen1.jpg' },
      { type: 'image', url: 'the_little_kite/the_little_kite_screen3.jpg' },
      { type: 'image', url: 'the_little_kite/the_little_kite_screen2.jpg' },
      { type: 'image', url: 'the_little_kite/the_little_kite_screen4.jpg' },
      { type: 'image', url: 'the_little_kite/the_little_kite_screen5.jpg' },
      { type: 'image', url: 'the_little_kite/the_little_kite_screen6.jpg' },
      { type: 'image', url: 'the_little_kite/the_little_kite_screen7.jpg' },
      { type: 'image', url: 'the_little_kite/the_little_kite_screen8.jpg' },
      { type: 'image', url: 'the_little_kite/the_little_kite_screen9.jpg' },
      { type: 'image', url: 'the_little_kite/the_little_kite_screen10.jpg' },
    ]
  },
  {
    id: 'octave',
    category: 'experimental-games',
    image: 'octave_ava.png',
    name: 'Octave',
    langKey: 'octave_description',
    steamLink: 'https://store.steampowered.com/app/537700',
    itchLink: 'https://anatolii.itch.io/octave',
    media: [
      { type: 'video', youtubeId: 'iDJlMMpG4fM' },
      { type: 'video', youtubeId: '7Qf00pf0af8' },
      { type: 'image', url: 'octave/octave_screen1.jpg' },
      { type: 'image', url: 'octave/octave_screen3.jpg' },
      { type: 'image', url: 'octave/octave_screen2.jpg' },
      { type: 'image', url: 'octave/octave_screen4.jpg' },
      { type: 'image', url: 'octave/octave_screen5.jpg' }
    ]
  },
  {
    id: 'the-kite',
    category: 'story-based-games',
    image: 'the_kite_ava.png',
    name: 'The Kite',
    langKey: 'the_kite_description',
    steamLink: 'https://store.steampowered.com/app/968700/The_Kite',
    itchLink: 'https://anatolii.itch.io/the-kite',
    media: [
      { type: 'video', youtubeId: 'Qz5IeAoQE34' },
      { type: 'image', url: 'the_kite/the_kite_screen1.jpg' },
      { type: 'image', url: 'the_kite/the_kite_screen3.jpg' },
      { type: 'image', url: 'the_kite/the_kite_screen2.jpg' },
      { type: 'image', url: 'the_kite/the_kite_screen4.jpg' },
      { type: 'image', url: 'the_kite/the_kite_screen5.jpg' }
    ]
  },
];
